lzc-sdk-version: '0.1'
package: com.selfstudio.{{PROJECT_NAME_LOWER}}
version: {{VERSION}}
min_os_version: 1.3.8
name: {{PROJECT_NAME}}
description: (LazyCat Auto-build) {{PROJECT_DESCRIPTION}}
license: {{LICENSE}}
homepage: {{PROJECT_HOMEPAGE}}
author: {{AUTHOR}}
application:
  subdomain: {{SUBDOMAIN}}
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://{{SERVICE_NAME}}:{{PORT}}/
services:
  {{SERVICE_NAME}}:
    image: registry.lazycat.cloud/{{USERNAME}}/{{UPSTREAM_IMAGE}}
    environment:
      # TODO: 添加环境变量
    binds:
      # TODO: 添加数据卷挂载
locales:
  en:
    name: {{PROJECT_NAME}}
    description: (LazyCat Auto-build) {{PROJECT_DESCRIPTION}}
  zh:
    name: {{PROJECT_NAME}}
    description: （懒猫微服自动构建）{{PROJECT_DESCRIPTION_ZH}}
